sudo: required

services:
  - docker

before_install:
  - cp ./ashlar/.env.example ./ashlar/.env
  - cp ./frontend/.env.example ./frontend/.env

install:
  - ./scripts/update

script:
  - ./scripts/test
