version: '3'

services:

  db:
    image: mdillon/postgis:10-alpine

  ashlar:
    build: ./ashlar
    depends_on:
      - db
    volumes:
      - ./ashlar:/opt/ashlar
    entrypoint: python
    command: manage.py wait_for_db_and_runserver
    ports:
      - "8000:8000"
    env_file: ./ashlar/.env

  editor:
    build: ./schema_editor
    depends_on:
      - ashlar
    volumes:
      - ./schema_editor:/opt/schema_editor
    ports:
      - "9000:9000"
      - "35731:35731"
    entrypoint: grunt
    command: serve
