version: '3'

services:
  db:
    image: mdillon/postgis:10-alpine
  ashlar-server:
    build: ./ashlar-server
    depends_on:
      - db
    volumes:
      - ./ashlar-server:/opt/ashlar-server
    entrypoint: python
    command: manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: ./ashlar-server/.env
