version: '3'

services:

  db:
    image: mdillon/postgis:10-alpine

  ashlar-server:
    build: ./ashlar-server
    depends_on:
      - db
    volumes:
      - ./ashlar-server:/opt/ashlar-server
    entrypoint: python
    command: manage.py wait_for_db_and_runserver
    ports:
      - "8000:8000"
    env_file: ./ashlar-server/.env

  schema-editor:
    image: node:8.11-slim
    working_dir: /usr/src/schema-editor
    ports:
      - "4567:4567"
    volumes:
        - ./schema-editor/app:/usr/src/schema-editor
        # Not sure what this does yet?
        - ./schema-editor/nginx/srv/dist:/usr/src/schema-editor/static
        - ./schema-editor/dist:/usr/dist/schema-editor
        # Ensure node_modules cache doesn't clash with other jobs on CI.
        - /var/cache/project-name-node-modules:/usr/src/node_modules
    command: yarn run dev-server
