version: '3'

services:
  db:
    image: mdillon/postgis:9.4
    ports:
      - "5432"
  ashlar-server:
    build: ./ashlar-server
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./ashlar-server:/opt/ashlar-server
