version: '3'

services:

  db:
    image: mdillon/postgis:10-alpine

  ashlar-server:
    build: ./ashlar-server
    depends_on:
      - db
    volumes:
      - ./ashlar-server:/opt/ashlar-server
    entrypoint: python
    command: manage.py wait_for_db_and_runserver
    ports:
      - "8000:8000"
    env_file: ./ashlar-server/.env

  schema-editor:
    build: ./schema-editor
    volumes:
      - ./schema-editor:/opt/schema-editor
    entrypoint: gunicorn
    command: schema_editor:app -w1 -b:4567 -kgevent
    ports:
      - "4567:4567"
    env_file: ./schema-editor/.env
