version: '3'

services:

  db:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim

  ashlar:
    build: ./ashlar
    depends_on:
      - db
    volumes:
      - ./ashlar:/opt/ashlar
    entrypoint: python
    command: manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: ./ashlar/.env
    environment:
      - PYTHONUNBUFFERED=0  # Do not buffer output (allows Docker to stream stdout)

  editor:
    build: ./schema_editor
    depends_on:
      - ashlar
    volumes:
      - ./schema_editor:/opt/schema_editor
    ports:
      - "9000:9000"
      - "35731:35731"
    entrypoint: grunt
    command: serve

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/opt/frontend
    depends_on:
      - ashlar
    entrypoint: gunicorn
    command: app:application -w1 -b:4567 -kgevent
    ports:
      - "4567:4567"
    env_file: ./frontend/.env

  loaddata:
    build: ./scripts/sample_data
    volumes:
      - ./scripts/sample_data:/opt/loaddata
    workdir:
      - /opt/loaddata
    depends_on:
      - ashlar
    command: python loaddata.py
