version: '3'

services:
  db:
    image: mdillon/postgis:9.4
  ashlar-server:
    build: ./ashlar-server
    depends_on:
      - db
    volumes:
      - ./ashlar-server:/opt/ashlar-server
    command: ashlar_server.wsgi -w3 -b:8000 -kgevent
    ports:
      - "8000:8000"
    env_file: ./ashlar-server/.env
