#!/bin/bash

set -e

if [[ -n "${ASHLAR_BLUEPRINT_DEBUG}" ]]; then
    set -x
fi

# Import database methods from the directory path of this script
CURDIR="${BASH_SOURCE%/*}"
. "${CURDIR}/_init_db.sh"

function usage() {
    echo -n "Usage: $(basename "$0")

Builds and pulls container images using docker-compose, and runs database migrations.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Build containers.
        docker-compose build

        # Run migrations.
        init_db
        docker-compose run --rm ashlar manage.py migrate
    fi
fi
