#!/bin/bash

set -e

if [[ -n "${ASHLAR_BLUEPRINT_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Builds and pulls container images using docker-compose, and runs database migrations.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Build containers.
        docker-compose build

        # The db service is needed to run database migrations, but it doesn't
        # reliably start up in time. Start it in the background and wait 15
        # seconds to make sure that Postgres is available for migrations.
        docker-compose run -d db
        echo "Waiting for database service to start..."
        sleep 30

        echo "Running migrations..."
        docker-compose run ashlar-server manage.py migrate

        docker-compose stop db

        # Install NPM modules.
        docker-compose run --rm --no-deps schema-editor yarn
    fi
fi
